#!/usr/bin/env zsh

# This script assembles the folder structure for the mission file. It will then attempt to detect what PBO tool is available and use that to pack the mission file.

# Global variables
cwd=$(pwd)
# eventually will be a list of all the mission setups available for each map available
missionNames=("2nd-platoon-private-zeus-nam" "dummy")
supportedMaps=("Cam_Lao_Nam" "example")
missionFolders=()
for map in "${supportedMaps[@]}"
do
    for missionName in "${missionNames[@]}"
    do
        local mapFolder="${missionName}.${map}"
        # if the source mission folder does not exist, continue the loop, skipping this mission.map combo
        if [ ! -d "${mapFolder}" ]; then
            echo "Skipping ${mapFolder} as it does not exist."
            continue
        fi
        missionFolders+=("${mapFolder}")
    done
done
# create temp folder with fallback for macos
tempFolder=$(mktemp -d 2>/dev/null || mktemp -d -t 'FirstCAVBuildTmp')
# detect PBO tool and set it to the variable pboTool
pboTool=""
if command -v armake2 &> /dev/null
then
    pboTool="armake2"
else
    echo "No PBO tool found. Please install armake2."
    exit 1
fi

# MARK: - Functions
function setupTempFolder {
    # Create mission folder(s) in temp folder
    for mapFolder in "${missionFolders[@]}"
    do
        # if the source mission folder does not exist, continue the loop, skipping this mission.map combo
        if [ ! -d "${mapFolder}" ]; then
            echo "Skipping ${mapFolder} as it does not exist."
            continue
        fi
        local targetFolder="${tempFolder}/${mapFolder}"
        # if the target folder exists, remove it
        if [ -d "${targetFolder}" ]; then
            rm -rf "${targetFolder}"
        fi
        cp -r "${mapFolder}" "${tempFolder}/"
        cp -r "FirstCAV" "${targetFolder}/"
        copyParadigm "${targetFolder}/"
    done
}

function copyParadigm {
    local missionFolder=$1
    cp -r "paradigm" "${missionFolder}"
}

function packMissions {
    # Pack the mission(s)
    cd "${tempFolder}"
    for mapFolder in "${missionFolders[@]}"
    do
        # if the source mission folder does not exist, continue the loop, skipping this mission.map combo
        if [ ! -d "${mapFolder}" ]; then
            echo "Skipping ${mapFolder} as it does not exist."
            continue
        fi
        echo "Packing ${mapFolder}"
        $pboTool pack "${mapFolder}" "${mapFolder}.pbo"
    done
    cd "${cwd}"
}

function updateGitSubmodules {
    # if the .submodules-updated file exists, quietly exit this function and continue the script
    if [ -f "${cwd}/.submodules-updated" ]; then
        return
    fi
    # Update git submodules
    git submodule update --init --recursive
    touch "${cwd}/.submodules-updated"
}

function moveArtifacts {
    # Move the artifacts to the build folder
    cp ${tempFolder}/*.pbo "${cwd}/build/"
    # mv "${tempFolder}/*.zip" "${cwd}/build/"
}

function cleanup {
    # Cleanup
    rm -rf "${tempFolder}"
}

# MARK: - Main function
function main {
    updateGitSubmodules
    setupTempFolder
    echo "Temp folder: ${tempFolder}"
    packMissions
    mkdir -p "${cwd}/build"
    moveArtifacts
    # if DEBUG is set, do not cleanup the temp folder
    if [ -z "$DEBUG" ]; then
        cleanup
    fi
}

# Run the main function
main